log = "debug"
sleeptime = 1
error_post = true

[slack_update_post]
text = "test"
username = "bot"
icon_emoji = ":sushi:"
channel = "#test"
link_names = true

[slack_error_post]
text = "error"
username = "bot"
icon_emoji = ":ghost:"
channel = "#test"
link_names = true

[slack_start_post]
text = "Running tonkotsu..."
username = "bot"
icon_emoji = ":ghost:"
channel = "#test"
link_names = true

[webhook]
url = "webhook_url"

[ios]
app_id = "id667861049"
country = "jp"

[android]
package = "com.mercariapp.mercari"
